export DISABLE_AUTO_UPDATE=true

export EDITOR="nvim"
export MANPAGER="nvim +Man!"
export VISUAL="nvim"

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.config/zsh"
export TERM=xterm-256color

ZSH_THEME="my"

plugins=(git)

if [[ "$TMUX" == "" ]]; then
    ~/.config/scripts/tmux-session-dispensary.sh ~
fi

source $ZSH/oh-my-zsh.sh
source "$HOME/.config/zsh/init.zsh"
