export DISABLE_AUTO_UPDATE=true

export EDITOR="nvim"
export MANPAGER="nvim +Man!"
export VISUAL="nvim"

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.config/zsh"
export TERM=xterm-256color

export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/ripgreprc"

export EXERCISM_CONFIG_HOME="$HOME/documents/projects/exercism/config"

ZSH_THEME="my"

plugins=(git)

if [[ "$TMUX" == "" ]]; then
    ~/.config/scripts/tmux-session-dispensary.sh ~
fi

source $ZSH/oh-my-zsh.sh
source "$HOME/.config/zsh/init.zsh"
# source "$HOME/.local/share/bob/env/env.sh" 2>/dev/null
