foreground #cdcdcd
background #141415

cursor #524f67
cursor_text_color #e0def4

selection_foreground #cdcdcd
selection_background #333738

color0  #141415
color8  #606079

# red
color1  #d8647e
color9  #d8647e

# green
color2  #7fa563
color10 #7fa563

# yellow
color3  #e0a363
color11 #f3be7c

# blue
color4  #6e94b2
color12 #7e98e8

# magenta
color5  #bb9dbd
color13 #bb9dbd

# cyan
color6  #9bb4bc
color14 #b4d4cf

# white
color7  #cdcdcd
color15 #c3c3d5
